<!DOCTYPE employees [
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name,department,address?,phone*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
]>
<employees>
	<employee>
		<name>Aditya Dahal</name>
		<department>IT Department</department>
		<address>Kamaladi</address>
	</employee>
	<employee>
		<name>Prasanna Thapa</name>
		<department>Busineess Department</department>
		<phone>123456789</phone>
		<phone>987654321</phone>
	</employee>
</employees>